# Generated by Django 5.0.4 on 2024-04-16 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='activity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='python_tutorial.lesson'),
        ),
    ]
