# Generated by Django 5.0.4 on 2024-04-16 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0002_lesson_questionnaire_activity_questionnaire_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='type',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='type',
            new_name='topic',
        ),
    ]
