# Generated by Django 5.0.4 on 2024-04-16 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0004_remove_questionnaire_activity_questionnaire_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='paragraph',
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('topic', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='python_tutorial.lesson')),
            ],
        ),
    ]
