# Generated by Django 5.0.4 on 2024-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0006_rename_paragraph_content_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='code_example',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='code_example',
            field=models.TextField(null=True),
        ),
    ]
