# Generated by Django 5.0.4 on 2024-04-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0009_rename_code_example_activity_data_pym_src_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='data_pym_src',
            new_name='compiler_src',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='script_src',
        ),
    ]
