# Generated by Django 5.0.4 on 2024-04-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0016_alter_content_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='error_code_example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
