# Generated by Django 5.0.4 on 2024-04-16 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0003_rename_type_lesson_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='activity',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('topic', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='python_tutorial.lesson')),
            ],
        ),
    ]
