# Generated by Django 5.0.4 on 2024-04-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_tutorial', '0011_yourmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='UploadImage',
        ),
    ]
